hats_train:
			CUDA_VISIBLE_DEVICES=" " python src/main.py \
			--feature_list return \
			--data_type $(data_type) \
			--test_phase $(test_phase) \
			--save_dir $(save_dir) \
			--label_proportion 1 1 1 \
